/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightPackage;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JToggleButton;

/**
 *
 * @author dua laptop
 */
public class Customer extends javax.swing.JFrame {

    Flight flight;
    ArrayList<Passenger> passengers;
    ArrayList<JToggleButton> seats;

    String firstName, lastName, phone, CNIC;
    int PNR;
    Customer customer;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    public Customer(Flight flight, ArrayList<Passenger> passengers, ArrayList<JToggleButton> seats) {
        initComponents();
        this.flight = flight;
        this.passengers = passengers;
        this.seats = seats;
    }

    public Customer(Flight flight, ArrayList<Passenger> passengers, Customer customer, ArrayList<JToggleButton> seats) {
        initComponents();
        this.flight = flight;
        this.passengers = passengers;
        this.customer = customer;
        // seat because when going from pass to cust, seat will be passed and when going back from cust to passenger, the new object creation will again have seats passed 
        // because it will be needed when going from passenger to seats.
        this.seats = seats;

        firstNameField.setText(customer.firstName);
        lastNameField.setText(customer.lastName);
        cnicField.setText(customer.CNIC);
        phoneField.setText(customer.phone);

    }

    public Customer(Customer oldCustomer) {
        this.firstName = oldCustomer.firstName;
        this.lastName = oldCustomer.lastName;
        this.CNIC = oldCustomer.CNIC;
        this.phone = oldCustomer.phone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        cnicField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        OkButton = new javax.swing.JButton();
        firstL = new javax.swing.JLabel();
        lastL = new javax.swing.JLabel();
        cnicL = new javax.swing.JLabel();
        phoneL = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara Light", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Customer Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 570, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 122, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Last  Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("CNIC#");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Phone#");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        firstNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        firstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 250, 30));

        lastNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 250, 30));

        cnicField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        cnicField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicFieldFocusLost(evt);
            }
        });
        cnicField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnicFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnicFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cnicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 250, 30));

        phoneField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 250, 30));

        OkButton.setBackground(new java.awt.Color(255, 255, 255));
        OkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Redo_52px.png"))); // NOI18N
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 70, 60));

        firstL.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        firstL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(firstL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 320, -1));

        lastL.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        lastL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lastL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 320, -1));

        cnicL.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        cnicL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(cnicL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 390, -1));

        phoneL.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        phoneL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(phoneL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 340, -1));

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Undo_52px.png"))); // NOI18N
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 70, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 930, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/panel.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 550));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed

        customer = new NewCustomer();

        customer.firstName = firstNameField.getText();
        customer.lastName = lastNameField.getText();
        customer.phone = phoneField.getText();
        customer.CNIC = cnicField.getText();

        if (firstNameField.getText().trim().isEmpty()) {
            firstL.setText("Enter your First Name");
        }
        if (lastNameField.getText().trim().isEmpty()) {
            lastL.setText("Enter your Last Name");
        }
        if (cnicField.getText().length() == 0) {
            cnicL.setText("Enter your CNIC No.");
        } else if ((cnicField.getText().length() != 13)) {
            cnicL.setText("CNIC No. should be 13 digits");
        }
        if (phoneField.getText().trim().isEmpty()) {
            phoneL.setText("Enter your Phone No.");
        } 
        if (!(firstNameField.getText().trim().isEmpty()) && !(lastNameField.getText().trim().isEmpty()) && (cnicField.getText().length() == 13) && !(phoneField.getText().trim().isEmpty())) {

            try {

                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                Connection con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");

                String queryCheck = "SELECT * FROM Customer WHERE CNIC='" + cnicField.getText() + "'";
                PreparedStatement pst = con.prepareStatement(queryCheck);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    customer = new OldCustomer(customer);
                    JOptionPane.showMessageDialog(this, "You appear to be an existing customer! Avail 20% discount at payment!", "Welcome Back!", INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Pleased to have you as part of our family! Stay in touch to avail exclusive discounts!", "Welcome!", INFORMATION_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }

            new Payment(flight, passengers, customer, seats).setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_OkButtonActionPerformed

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
        // TODO add your handling code here:
        char c2 = evt.getKeyChar();
        if (!(Character.isDigit(c2) || (c2 == KeyEvent.VK_BACK_SPACE) || c2 == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void firstNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameFieldKeyReleased
        // TODO add your handling code here:
        firstL.setText("");
    }//GEN-LAST:event_firstNameFieldKeyReleased

    private void lastNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyReleased
        // TODO add your handling code here:
        lastL.setText("");
    }//GEN-LAST:event_lastNameFieldKeyReleased

    private void cnicFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicFieldKeyReleased
        // TODO add your handling code here:
        cnicL.setText("");
    }//GEN-LAST:event_cnicFieldKeyReleased

    private void phoneFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyReleased
        // TODO add your handling code here:
        phoneL.setText("");
    }//GEN-LAST:event_phoneFieldKeyReleased

    private void cnicFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicFieldKeyTyped

        char ac = evt.getKeyChar();
        if (!(Character.isDigit(ac)) || evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            getToolkit().beep();
            evt.consume();
            cnicField.setEditable(true);
        }

    }//GEN-LAST:event_cnicFieldKeyTyped

    private void cnicFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFieldFocusLost
        if(cnicField.getText().length()==0)
            cnicL.setText("Enter your CNIC No.");
        else if ((cnicField.getText().length() != 13)) {
            cnicL.setText("CNIC No. should be 13 digits");
        }
    }//GEN-LAST:event_cnicFieldFocusLost

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new Passenger(flight, seats, passengers).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backbuttonActionPerformed

    private void firstNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            firstNameField.setEditable(true);
        } else {
            firstNameField.setEditable(false);
        }
    }//GEN-LAST:event_firstNameFieldKeyTyped

    private void lastNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyTyped
        char c1 = evt.getKeyChar();
        if (Character.isLetter(c1) || Character.isWhitespace(c1) || Character.isISOControl(c1)) {
            lastNameField.setEditable(true);
        } else {
            lastNameField.setEditable(false);
        }
    }//GEN-LAST:event_lastNameFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField cnicField;
    private javax.swing.JLabel cnicL;
    private javax.swing.JLabel firstL;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lastL;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneL;
    // End of variables declaration//GEN-END:variables
}

class NewCustomer extends Customer {

    public NewCustomer() {
    }

    public NewCustomer(Flight flight, ArrayList<Passenger> passengers, ArrayList<JToggleButton> seats) {
        super(flight, passengers, seats);

    }

    public NewCustomer(Flight flight, ArrayList<Passenger> passengers, Customer customer, ArrayList<JToggleButton> seats) {
        super(flight, passengers, customer, seats);
    }

}

class OldCustomer extends Customer {

    public OldCustomer() {

    }

    public OldCustomer(Customer customer) {
        super(customer);
    }
}
