
package FlightPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saba fatima
 */
public class FlightSchedule extends javax.swing.JFrame {

    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    Date date_today;
    
    public FlightSchedule() {
        initComponents();
        table.setDefaultEditor(Object.class, null);
        try {
            this.date_today = sdf.parse(sdf.format(new Date()));
        } catch (ParseException ex) {
            Logger.getLogger(FlightSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        srcBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dstBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        srcL = new javax.swing.JLabel();
        dstL = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara Light", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Schedule");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 420, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel2.setText("SOURCE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 25));

        srcBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        srcBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta" }));
        srcBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                srcBoxMouseReleased(evt);
            }
        });
        getContentPane().add(srcBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel3.setText("DESTINATION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        dstBox.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        dstBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta" }));
        dstBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dstBoxMouseReleased(evt);
            }
        });
        getContentPane().add(dstBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 150, 28));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 104, 30));

        jScrollPane1.setHorizontalScrollBar(null);

        table.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight_ID", "Source", "Destination", "Date", "Departure Time", "Arrival Time", "Economy Fare", "Business Fare", "Available Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(204, 204, 204));
        table.setRowHeight(22);
        table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 910, 210));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("The fares are in Pakistani Ruppees.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 260, 36));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Children below 8 years of age will be subjected to Child Fare. ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 510, 30));

        srcL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(srcL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, -1));

        dstL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(dstL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 242, -1));

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Undo_52px.png"))); // NOI18N
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 60, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/panel.big.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 540));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background.big.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 940, 100));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Child Fare is 50% of the Adult Fare. Adult Fare is shown in the table. ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 510, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background1.big.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(srcBox.getSelectedIndex()<=0){
            srcL.setText("Please select an option from Source...");
        }
        if(dstBox.getSelectedIndex()<=0){
             dstL.setText("Please select an option from Destination...");
        }
        if((srcBox.getSelectedIndex()>0) && (dstBox.getSelectedIndex()>0)){
        try{
           
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        Connection con= DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");

        
        
        
        PreparedStatement pst=con.prepareStatement("SELECT Flight_ID,Source,Destination,Date,Departure_Time,Arrival_Time,Economy_fare,Business_fare,Available_Seats FROM Schedule WHERE Source='"+(String)srcBox.getSelectedItem()+"' AND Destination='"+(String)dstBox.getSelectedItem()+"'");    
       
        DefaultTableModel model = new DefaultTableModel(new String[]{"Flight_ID","Source","Destination","Date","Departure Time","Arrival Time","Economy Fare","Business Fare","Available Seats"},0);
        
        //String str= "SELECT * FROM Schedule WHERE To = '"+ToBox.getSelectedItem()+"' and From = '"+FromBox.getSelectedItem()+"'";
        
        ResultSet rs=pst.executeQuery();
        
                    int i=0;
                    if(rs.next()){
                        
                    do{
                        int num=rs.getDate("Date").compareTo(date_today);
                        if(num>=0){
                            i++;
                            model.addRow(new Object[]{rs.getString("Flight_ID"),rs.getString("Source"),rs.getString("Destination"),sdf.format(rs.getDate("Date")),rs.getTime("Departure_Time"),rs.getTime("Arrival_Time"),rs.getString("Economy_fare"),rs.getString("Business_fare"),rs.getString("Available_Seats")});
                            table.setModel(model);
                        }
                    }while(rs.next()==true);
                    }	
                    
                    if(i==0){
                        JOptionPane.showMessageDialog(null,"No Flights between Source and Destination");
                    }
                    
                   	
        
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void srcBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srcBoxMouseReleased
        // TODO add your handling code here:
        srcL.setText("");
    }//GEN-LAST:event_srcBoxMouseReleased

    private void dstBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstBoxMouseReleased
        // TODO add your handling code here:
        dstL.setText("");
    }//GEN-LAST:event_dstBoxMouseReleased

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       
        this.setVisible(false);
        new MainFrame().setVisible(true);
      
        
    }//GEN-LAST:event_backbuttonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightSchedule().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox dstBox;
    private javax.swing.JLabel dstL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox srcBox;
    private javax.swing.JLabel srcL;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
