/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Acer
 */
public class Flight extends javax.swing.JFrame {

    String Flight_ID;
    int totalPassengers;

    /**
     * Creates new form Flight
     */
    public Flight() {
        initComponents();

    }

    public Flight(Flight f) {
        initComponents();
        this.Flight_ID = f.Flight_ID;
        this.totalPassengers = f.totalPassengers;
        flightIDField.setText(this.Flight_ID);
        passengerBox.setSelectedIndex(this.totalPassengers);

    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightIDField = new javax.swing.JTextField();
        seatButton = new javax.swing.JButton();
        passengerBox = new javax.swing.JComboBox<>();
        flightL = new javax.swing.JLabel();
        tpL = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Candara Light", 3, 55)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Fight Information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 500, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Flight ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Total Passengers");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, -1));

        flightIDField.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        flightIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                flightIDFieldKeyReleased(evt);
            }
        });
        getContentPane().add(flightIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 230, -1));

        seatButton.setBackground(new java.awt.Color(255, 255, 255));
        seatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Redo_52px.png"))); // NOI18N
        seatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, 70, 60));

        passengerBox.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        passengerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5" }));
        passengerBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passengerBoxMouseReleased(evt);
            }
        });
        getContentPane().add(passengerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 230, -1));

        flightL.setFont(new java.awt.Font("Candara Light", 2, 18)); // NOI18N
        flightL.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(flightL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 260, 30));

        tpL.setFont(new java.awt.Font("Candara Light", 2, 18)); // NOI18N
        tpL.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(tpL, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 260, 30));

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Undo_52px.png"))); // NOI18N
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 477, 70, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/panel.jpg"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(417, 550));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 540));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 3, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 940, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background1.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(1030, 550));
        jLabel4.setMinimumSize(new java.awt.Dimension(1030, 550));
        jLabel4.setPreferredSize(new java.awt.Dimension(1030, 550));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatButtonActionPerformed
        if (flightIDField.getText().trim().isEmpty()) {
            flightL.setText("Enter Flight ID");
        }
        if (passengerBox.getSelectedIndex() <= 0) {
            tpL.setText("Please select total passengers");
        }
        if(!(flightIDField.getText().trim().isEmpty()) && (passengerBox.getSelectedIndex() > 0)){

            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");

                Flight flight = new Flight();

                flight.Flight_ID = flightIDField.getText();
                flight.totalPassengers = Integer.parseInt((String) passengerBox.getSelectedItem());

                String queryCheck = "SELECT * FROM Schedule WHERE Flight_ID = ?";
                pst = con.prepareStatement(queryCheck);
                pst.setString(1, flight.Flight_ID);
                rs = pst.executeQuery();

                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "This Flight_ID doesnot exist!", "Flight Information", ERROR_MESSAGE);
                } else {
                    if (rs.getInt("Available_Seats") == 0) {
                        JOptionPane.showMessageDialog(this, "This flight is commpletely booked! Choose another one!", "Flight Information", ERROR_MESSAGE);
                    } else if ((flight.totalPassengers) > 5) {
                        JOptionPane.showMessageDialog(this, "More than 5 seats cannot be booked once!", "Flight Information", ERROR_MESSAGE);
                    } else {

                        this.setVisible(false);
                        new Seat(flight).setVisible(true);

                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Flight.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Flight.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_seatButtonActionPerformed

    private void flightIDFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_flightIDFieldKeyReleased
        // TODO add your handling code here:
        flightL.setText("");
    }//GEN-LAST:event_flightIDFieldKeyReleased

    private void passengerBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerBoxMouseReleased
        // TODO add your handling code here:
        tpL.setText("");
    }//GEN-LAST:event_passengerBoxMouseReleased

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        this.setVisible(false);
        new MainFrame().setVisible(true);


    }//GEN-LAST:event_backbuttonActionPerformed

    //public void setSeat(Seat seat){
    //  this.seat=seat;
    //}
    /* public String getFlightID(){
        return Flight_ID;
    }
    
    public int getAdult(){
        return adult;
    }
    
    public int getChild(){
        return child;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField flightIDField;
    private javax.swing.JLabel flightL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> passengerBox;
    private javax.swing.JButton seatButton;
    private javax.swing.JLabel tpL;
    // End of variables declaration//GEN-END:variables
}
