/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class myBookings extends javax.swing.JFrame {
    Ticket CP;
    /**
     * Creates new form myBookings
     */
    public myBookings() {

        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

  

    public myBookings(String pnr) {

        initComponents();
        pnrField.setText(pnr);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnrField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        showButton = new javax.swing.JButton();
        pnrL = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara Light", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("My Bookings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 360, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Enter your PNR No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, -1));

        pnrField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pnrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnrFieldKeyReleased(evt);
            }
        });
        jPanel1.add(pnrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 270, -1));

        table1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PNR_No", "Passport No.", "Full_Name", "Gender", "DOB", "Country", "Seat No.", "Cabin", "PassengerType", "Payment", "ETKT", "Flight_ID"
            }
        ));
        table1.setGridColor(new java.awt.Color(204, 204, 204));
        table1.setRowHeight(22);
        table1.setSelectionBackground(new java.awt.Color(196, 196, 240));
        table1.setUpdateSelectionOnSort(false);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 900, 150));

        showButton.setBackground(new java.awt.Color(255, 255, 255));
        showButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        jPanel1.add(showButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 219, -1, 40));

        pnrL.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        pnrL.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(pnrL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 222, -1));

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Undo_52px.png"))); // NOI18N
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 60, 50));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Click a record to print or cancel a ticket.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 737, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/panel.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 540));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 940, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background1.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        if (pnrField.getText().trim().isEmpty()) {
            pnrL.setText("Please enter your PNR No.");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");

                String pnr = pnrField.getText();
                pst = con.prepareStatement("SELECT PNR_No,PassportNo,Full_Name,gender,DOB,Country,SeatNo,Cabin,PassengerType,Payment,ETKT,Flight_ID FROM Passenger WHERE PNR_No='" + pnr + "'");
                DefaultTableModel MD = new DefaultTableModel(new String[]{"PNR No.", "Passport No.", "Full Name", "Gender", "DOB", "Country", "Seat No", "Cabin", "Passenger Type", "Payment", "ETKT", "Flight_ID"}, 0);
                rs = pst.executeQuery();

                if (rs.next()) {

                    do {
                        MD.addRow(new Object[]{rs.getString("PNR_No"), rs.getString("PassportNo"), rs.getString("Full_Name"), rs.getString("gender"), rs.getString("DOB"), rs.getString("Country"), rs.getString("SeatNo"), rs.getString("Cabin"), rs.getString("PassengerType"), rs.getString("Payment"), rs.getString("ETKT"), rs.getString("Flight_ID")});
                        table1.setModel(MD);
                    } while (rs.next() == true);
                } else {
                    JOptionPane.showMessageDialog(null, "You have No Flights Booked", "", ERROR_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(myBookings.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(myBookings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_showButtonActionPerformed

    private void pnrFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnrFieldKeyReleased
        // TODO add your handling code here:
        pnrL.setText("");
    }//GEN-LAST:event_pnrFieldKeyReleased

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int index = table1.getSelectedRow();
        TableModel M = table1.getModel();

        String name = M.getValueAt(index, 2).toString();
        String passport = M.getValueAt(index, 1).toString();
        String dob = M.getValueAt(index, 4).toString();
        String count = M.getValueAt(index, 5).toString();
        String seatNo = M.getValueAt(index, 6).toString();
        String cabin = M.getValueAt(index, 7).toString();
        String id = M.getValueAt(index, 11).toString();

        CP = new Ticket(pnrField.getText());
        this.setVisible(false);
        CP.setVisible(true);
        CP.pack();
        CP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        CP.nameL.setText(name);
        CP.passL.setText(passport);
        CP.dobL.setText(dob);
        CP.countryL.setText(count);
        CP.seatL.setText(seatNo);
        CP.cabins.setText(cabin);
        CP.flightL.setText(id);


    }//GEN-LAST:event_table1MouseClicked

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pnrField;
    private javax.swing.JLabel pnrL;
    private javax.swing.JButton showButton;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
