/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightPackage;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Lenovo
 */
public class Ticket extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String pnr;
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    java.util.Date date_today;
    /**
     * Creates new form CancelAndPrint
     */
    public Ticket() {
        initComponents();
    }

    public Ticket(String pnr) {
        initComponents();
        this.pnr = pnr;
         try {
            this.date_today = sdf.parse(sdf.format(new java.util.Date()));
        } catch (ParseException ex) {
            Logger.getLogger(FlightSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabinL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FlightF = new javax.swing.JLabel();
        SeatF = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        passL = new javax.swing.JLabel();
        dobL = new javax.swing.JLabel();
        countryL = new javax.swing.JLabel();
        flightL = new javax.swing.JLabel();
        seatL = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        cabinF = new javax.swing.JLabel();
        cabins = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        cabinL.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara Light", 3, 30)); // NOI18N
        jLabel1.setText("Passenger Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, 47));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Passport No.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Date of Birth:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Country:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        FlightF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        FlightF.setText("Flight ID:");
        jPanel1.add(FlightF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        SeatF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        SeatF.setText("Seat No.");
        jPanel1.add(SeatF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        nameL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        nameL.setText("name");
        jPanel1.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 249, 40));

        passL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        passL.setText("passport");
        jPanel1.add(passL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 249, 40));

        dobL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        dobL.setText("DOB");
        jPanel1.add(dobL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 249, 40));

        countryL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        countryL.setText("country");
        jPanel1.add(countryL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 267, 249, 40));

        flightL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        flightL.setText("flight");
        jPanel1.add(flightL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 249, 40));

        seatL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        seatL.setText("seat");
        jPanel1.add(seatL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 367, 249, 40));

        printButton.setBackground(new java.awt.Color(255, 255, 255));
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Print_48px.png"))); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel1.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 60, 50));

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Cancel_40px.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 60, 50));

        cabinF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cabinF.setText("Cabin:");
        jPanel1.add(cabinF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        cabins.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        cabins.setText("cabin");
        jPanel1.add(cabins, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 417, 229, 40));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/Undo_52px.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 60, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightPackage/images/blue background.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 610, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void cancel(){
        String nam = nameL.getText();
        String pass = passL.getText();
        
        
        
        int dialogButton = JOptionPane.YES_NO_OPTION;

        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel this flight?", "Warning", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
            
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");
                
               
                
                
                pst = con.prepareStatement("SELECT * FROM Passenger WHERE Full_Name='" + nam + "' AND PassportNo='" + pass + "' ");
                ResultSet r = pst.executeQuery();

                String Nameee = null;
                String PassNo = null;
                String gender = null;
                String dobb = null;
                String country = null;
                int pnrr = 0;
                String fligh = null;
                String sn = null;
                int etkt = 0;
                String cab = null;
                String passtype = null;
                int payment = 0;

                if (r.next()) {
                    Nameee = r.getString("Full_Name");
                    PassNo = r.getString("PassportNo");
                    gender = r.getString("gender");
                    dobb = r.getString("DOB");
                    country = r.getString("Country");
                    pnrr = r.getInt("PNR_No");
                    fligh = r.getString("Flight_ID");
                    sn = r.getString("SeatNo");
                    etkt = r.getInt("ETKT");
                    cab = r.getString("Cabin");
                    passtype = r.getString("PassengerType");
                    payment = r.getInt("Payment");

                }
                pst = con.prepareStatement("INSERT INTO CancelledPassengers(PNR_No,PassportNo,Full_Name,gender,DOB,Country,SeatNo,Cabin,PassengerType,Payment,ETKT,Flight_ID) values('" + pnrr + "','" + PassNo + "','" + Nameee + "','" + gender + "','" + dobb + "','" + country + "','" + sn + "','" + cab + "','" + passtype + "','" + payment + "','" + etkt + "','" + fligh + "')");
                pst.executeUpdate();

                pst = con.prepareStatement("DELETE * FROM Passenger WHERE PNR_No='" + pnrr + "' AND PassportNo='" + pass + "'");
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Your Flight has been Cancelled. Your fare plus cancellation charges will be refunded to your account within a week.", "", INFORMATION_MESSAGE);

                this.setVisible(false);
                new myBookings(pnr).setVisible(true);
                
                } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }
              

            }

            String seat = seatL.getText();
            String id = flightL.getText();
            int count = 0;
            try {

                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");
                pst = con.prepareStatement("SELECT * FROM Schedule WHERE Flight_ID = ?");
                pst.setString(1, id);
                ResultSet r = pst.executeQuery();
                if (r.next()) {
                    count = r.getInt("Available_Seats");
                }

                pst = con.prepareStatement("UPDATE Schedule SET Available_Seats ='" + (count + 1) + "'WHERE Flight_ID = '" + id + "'");
                pst.executeUpdate();

                pst = con.prepareStatement("UPDATE Seat SET " + seat + "='A' WHERE Flight_ID= '" + id + "'");
                pst.executeUpdate();

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    public PageFormat getPageFormat(PrinterJob pj) {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();

        double middleHeight = 8.0;
        double headerHeight = 2.0;
        double footerHeight = 2.0;
        double width = convert_CM_To_PPI(15);
        double height = convert_CM_To_PPI(headerHeight + middleHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(
                0,
                10,
                width,
                height - convert_CM_To_PPI(1)
        );

        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);

        return pf;
    }

    protected static double convert_CM_To_PPI(double cm) {
        return toPPI(cm * 0.393600787);
    }

    protected static double toPPI(double inch) {
        return inch * 72d;
    }

    public class TicketPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {
            int result = NO_SUCH_PAGE;

            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Flight_Database.accdb");

                if (pageIndex == 0) {

                    Graphics2D g2d = (Graphics2D) graphics;

                    g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

                    try {

                        int y = 20;
                        int yShift = 10;
                        int headerRectHeight = 15;
                        int headerRectHeighta = 40;

                        String id = flightL.getText();
                        String name = nameL.getText();
                        String seat = seatL.getText();
                        String cabin = cabins.getText();
                        String source = null;
                        String dest = null;
                        Date date = null;
                        Time depart = null;
                        Time arrive = null;
                        pst = con.prepareStatement("SELECT * FROM Schedule WHERE Flight_ID = ?");
                        pst.setString(1, id);
                        ResultSet rs = pst.executeQuery();
                        while (rs.next()) {
                            source = rs.getString("Source");
                            dest = rs.getString("Destination");
                            date = rs.getDate("Date");
                            depart = rs.getTime("Departure_Time");
                            arrive = rs.getTime("Arrival_Time");
                        }

                        int pnr = 0;
                        long ticket = 0;
                        pst = con.prepareStatement("SELECT * FROM Passenger WHERE Full_Name = ?");
                        pst.setString(1, name);
                        ResultSet rs1 = pst.executeQuery();
                        while (rs1.next()) {

                            pnr = rs1.getInt("PNR_No");

                            ticket = rs1.getLong("ETKT");
                        }

                        // System.out.println(ticket);
                        long difference;
                        if (arrive.getTime() >= depart.getTime()) {
                            difference = arrive.getTime() - depart.getTime() - 19800000;
                        } else {
                            difference = depart.getTime() - arrive.getTime() - 19800000;
                        }

                        Time time = new Time(difference);

                        g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                        g2d.drawString("                  ALPHA-AIRE                     ", 12, y);
                        y += yShift;
                        g2d.drawString("----------------------------------------------", 12, y);
                        y += yShift;
                        g2d.drawString(" " + name + " || " + " PNR: " + pnr, 12, y);
                        y += yShift;
                        g2d.drawString("----------------------------------------------", 12, y);
                        y += yShift;
                        g2d.drawString(" FLIGHT ID " + id + "                 " + date, 12, y);
                        y += yShift;
                        g2d.drawString("----------------------------------------------", 12, y);
                        y += headerRectHeight;
                        g2d.drawString(" DEPARTURE: " + source + " || "  + depart, 10, y);
                        y += yShift;
                        g2d.drawString(" ARRIVAL:   " + dest + "  || " + arrive, 10, y);
                        y += yShift;
                        g2d.drawString("                            ", 10, y);
                        y += yShift;
                        g2d.drawString(" SEAT: " + seat + "(" + cabin + ")        DURATION: " + time, 10, y);
                        y += yShift;
                        g2d.drawString("----------------------------------------------", 10, y);
                        y += yShift;
                        g2d.drawString(" NON STOP    " + source + " TO " + dest, 10, y);
                        y += yShift;
                        g2d.drawString("                                         ", 10, y);
                        y += yShift;
                        g2d.drawString("----------------------------------------------", 10, y);
                        y += yShift;
                        g2d.drawString(" TICKET NO:    " + ticket, 10, y);
                        y += yShift;
                        g2d.drawString("**********************************************", 10, y);
                        y += yShift;
                        

                    } catch (Exception r) {
                        r.printStackTrace();
                    }

                    result = PAGE_EXISTS;
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }

            return result;
        }
    }
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new TicketPrintable(), getPageFormat(pj));
        try {
            pj.print();

        } catch (PrinterException | NullPointerException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_printButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new myBookings(pnr).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlightF;
    private javax.swing.JLabel SeatF;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cabinF;
    public javax.swing.JLabel cabinL;
    public javax.swing.JLabel cabins;
    private javax.swing.JButton cancelButton;
    public javax.swing.JLabel countryL;
    public javax.swing.JLabel dobL;
    public javax.swing.JLabel flightL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel nameL;
    public javax.swing.JLabel passL;
    private javax.swing.JButton printButton;
    public javax.swing.JLabel seatL;
    // End of variables declaration//GEN-END:variables
}
